# Generated by Django 5.0.6 on 2024-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendshop_website', '0003_remove_category_sub_category_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('status', '-activate_date')},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='product_images/default-product-image.jpg', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default-product-image.jpg', upload_to='static/images/'),
        ),
    ]
