# Generated by Django 5.0.6 on 2024-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendshop_website', '0005_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='product_images/default-product-image.jpg', upload_to='uploaded_image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default-product-image.jpg', upload_to='uploaded_image/'),
        ),
    ]
