# Generated by Django 5.0.6 on 2024-06-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendshop_website', '0010_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
